### ISSUE TITLE
編譯原理建議

### ISSUE THREAD

**Issue by DominguitoLamo** [fuzhengwei/RoadMap#5]
个人觉得编译原理不要一开始就学理论, 最好先做一些简单的项目开始, 这样可以有直观的认识。市面上有不少实践书。我介绍两个开源比较好的项目:

Super Tiny Compiler: https://github.com/jamiebuilds/the-super-tiny-compiler

这是用js做的最简单的编译器, 麻雀虽小, 但五脏俱全, 几百行代码就完成了。

Crafting Interpreter: https://craftinginterpreters.com/

这本书就是利用java和c实现一款叫lox的动态语言, 通过实践, 可以了解基础的编译原理知识, 如有限状态自动机, AST, 利用访问者模式遍历AST等。这本书好像中文版翻译了几章。

**Comment by fuzhengwei** [comment]
收录完成：[https://github.com/fuzhengwei/RoadMap/blob/main/01-%E5%9F%BA%E7%A1%80/011-%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/3-%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86.md](https://github.com/fuzhengwei/RoadMap/blob/main/01-%E5%9F%BA%E7%A1%80/011-%E8%AE%A1%E7%AE%97%E6%9C%BA%E5%9F%BA%E7%A1%80/3-%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86/%E7%BC%96%E8%AF%91%E5%8E%9F%E7%90%86.md)
